#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;
#include "com_example_android_camera2basic_CvUtil.h"	// generated by javah

JNIEXPORT void JNICALL Java_com_example_android_camera2basic_CvUtil_processMat
  (JNIEnv *env, jclass thiz, jlong addrRgba){

    Mat* pMatRgb = (Mat*)addrRgba;

  int kernel_size = 3;
      Mat sharpen,dst,gray,grad_x, grad_y,gradient,blurred,thresh,closed,M;
      vector<vector<Point> > cnts;

      //Mat image = imread("pic4.jpg");

Mat image = *pMatRgb;

      if (image.empty())
      {
          cout << "Could not open or find the image" << endl;
          cin.get();
          //return -1;
      }

      Mat sharpen_kernel = Mat::ones( kernel_size, kernel_size, CV_32F )*-1;
      sharpen_kernel.at<float>(1,1)=9;
      filter2D(image, sharpen, -1 , sharpen_kernel );

      cv::fastNlMeansDenoising(sharpen, dst, 7, 21);
      cv::cvtColor(dst, gray, cv::COLOR_BGR2GRAY);

      threshold(gray, thresh,144, 255, cv::THRESH_BINARY);

      imshow("Oroginal", image);
      imshow("filter",thresh);


      waitKey(0);

      destroyAllWindows();

     // return 0;

  }


